### ISSUE TITLE
exampele file

### ISSUE THREAD

**Issue by yuerchang** [maahn/pamtra2#7]
I can't find the file ''COSMO_column_20170102.nc'' in the example of DesignDraft , could you send me this file? Thank you very much.

**Comment by maahn** [comment]
The Design draft is just the plan how the simulator should look like in the end, the code does not work because many functions are still missing. Similarly, the COSMO_column_20170102.nc file is just a place holder. I strongly recommend to use the much more mature, feature-complete, and better documented first version of pamtra: https://github.com/igmk/pamtra
